[package]
name = "tftpff"
version = "0.1.0"
edition = "2021"
description = "Firewall-friendly tftp server"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
env_logger = "0.9.0"
log = "0.4.14"
