[package]
name = "tftpff"
version = "0.1.0"
edition = "2021"
description = "Firewall-friendly tftp server"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
